default_stages: [pre-commit, pre-push]
default_language_version:
    python: python3.14
fail_fast: false
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-merge-conflict
    -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
    -   id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
    -   id: check-toml
    -   id: check-yaml
    -   id: check-json
        exclude: frontend/
    -   id: pretty-format-json
        args: [--autofix, --no-sort-keys]
        exclude: frontend/

- repo: local
  hooks:
    - id: pyright
      name: pyright
      entry: make
      language: system
      pass_filenames: false
      args:
        [typecheck]

- repo: local
  hooks:
    - id: format
      name: format
      entry: make
      language: system
      pass_filenames: false
      args:
        [fmt]

- repo: local
  hooks:
    - id: lint
      name: lint
      entry: make
      language: system
      pass_filenames: false
      args:
        [lint]
